### ISSUE TITLE
Login not working 1.1.0.8

### ISSUE THREAD

**Issue by BloodGozilla** [Dean2k/S.A.R.S#1]
I am trying to login with my vrchat username and password and the 2fa code but it always says login failed.

**Comment by Dean2k** [comment]
> I am trying to login with my vrchat username and password and the 2fa code but it always says login failed.

Make sure its a 2fa code from google auth or authy and not email as this is not supported

**Comment by BloodGozilla** [comment]
it is the code from google auth

**Comment by Dean2k** [comment]
then I have no idea, it works perfectly for me with or without an auth code attached. Logs in everytime.

If you are using a VPN make sure to login with the VPN on a browser first then use the app.

**Comment by BloodGozilla** [comment]
No VPN is used.

**Comment by BloodGozilla** [comment]
I fixed it. had to disable and reenable 2fa
