### ISSUE TITLE
Inquiry about relation to A.R.E.S

### ISSUE THREAD

**Issue by Sarirath** [Dean2k/S.A.R.S#2]
Is this in any way related to A.R.E.S. I ask this because I have a question about A.R.E.S.

I don't know how to contact the staff of the avatar recovery server without being in the server.

I apologize if this is a completely different project and I wasted your time looking at this.

**Comment by Sarirath** [comment]
For an explanation on why I need to contact the staff.
A friend of mine had requested that I use A.R.E.S to recover an avatar for him because he uses a remote pc in New York while he lives in Illinois. Due to him being in Illinois while he was logging into the server on a pc in New York, the server told him he couldn't access the server with a VPN connected.
He then requested that I log into his account on A.R.E.S and do it for him which then ended up getting me banned because the server detected multiple accounts being logged from the same location.

**Comment by Dean2k** [comment]
Server doesn't ban for using VPN's it just restricts you joining under a VPN, join without VPN and it'll be fine.
